kind: pipeline
type: docker
name: Deploy

services:
  - name: mariadb
    # https://hub.docker.com/_/percona
    pull: if-not-exists
    image: mariadb:11.0
    ports:
      - 3306
    environment:
      TZ: Europe/Moscow
      MYSQL_DATABASE: zdrava_testing
      MYSQL_USER: homestead
      MYSQL_PASSWORD: homestead
      MYSQL_ROOT_PASSWORD: root

  - name: docker
    pull: if-not-exists
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

clone:
  git:
    image: plugins/git:latest
    recursive: false

steps:
  - name: composer-install-dev
    image: laradock/workspace:master-8.2
    commands:
      - php -v
      - composer --version
      - chmod +w ./bootstrap/cache
      - composer install --prefer-dist --no-ansi --no-interaction --no-progress --ignore-platform-reqs
    when:
      event: push

  - name: frontend
    pull: if-not-exists
    image: node
    commands:
      - node -v
      - npm -v
      - yarn --version
      - yarn install
      - yarn run build

  - name: backend
    pull: if-not-exists
    # https://hub.docker.com/r/laradock/workspace/
    image: laradock/workspace:master-8.2
    commands:
      - php -v
      - cp .env.testing .env
      - php artisan key:generate
      - php artisan migrate
      - nohup php artisan serve --host 0.0.0.0 --port 80 &

  - name: code-sniffer
    image: cytopia/phpcs
    pull: always
    commands:
      - phpcs --version
      - phpcs --standard=phpcs.xml --runtime-set ignore_warnings_on_exit 1
    when:
      event: push

  - name: psalm
    image: laradock/workspace:master-8.2
    commands:
      - ./vendor/bin/psalm --version
      - ./psalm.sh
    when:
      event: push

  - name: rector
    image: laradock/workspace:master-8.2
    commands:
      - ./vendor/bin/rector --version
      - ./vendor/bin/rector process --dry-run --no-progress-bar
    when:
      event: push

  - name: phpunit
    image: laradock/workspace:master-8.2
    commands:
      - ./vendor/bin/phpunit --version
      - ./vendor/bin/phpunit --configuration phpunit.xml
    when:
      event: push

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: 192.168.1.254
      username: mpolr
      key:
        from_secret: SSH_PRIVATE_KEY
      script:
        - docker exec php82 sh -c "git config --global --add safe.directory /var/www/zdrava.online"
        - docker exec php82 sh -c "cd /var/www/zdrava.online && git pull --rebase origin master && composer install --optimize-autoloader"
        - docker exec php82 sh -c "cd /var/www/zdrava.online && php artisan migrate"
        - docker exec php82 sh -c "cd /var/www/zdrava.online && php artisan livewire:publish --assets"
        - docker exec php82 sh -c "cd /var/www/zdrava.online && yarn install && yarn run build"
